--DROP SEQUENCES IF EXISTS
DROP SEQUENCE USER_ID;
DROP SEQUENCE USER_STATUS_ID;
DROP SEQUENCE CLUB_ID;
DROP SEQUENCE CATEGORY_ID;
DROP SEQUENCE THREAD_ID;
DROP SEQUENCE GAMES_ID;
DROP SEQUENCE OPENING_ID;
DROP SEQUENCE STATUS_ID;
DROP SEQUENCE COMMENT_ID;

-- CREATE SEQUENCES FOR PRIMARY KEYS IN TABLES
CREATE SEQUENCE USER_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;
CREATE SEQUENCE USER_STATUS_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;
CREATE SEQUENCE CLUB_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;
CREATE SEQUENCE CATEGORY_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;
CREATE SEQUENCE THREAD_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;
CREATE SEQUENCE GAMES_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;
CREATE SEQUENCE OPENING_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;
CREATE SEQUENCE STATUS_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;
CREATE SEQUENCE COMMENT_ID INCREMENT BY 1 START WITH 1 MAXVALUE 100000;

-- DROP TABLES IF EXISTS
DROP TABLE USER_STATUS CASCADE CONSTRAINTS;
DROP TABLE OPENINGS CASCADE CONSTRAINTS;
DROP TABLE GAMES CASCADE CONSTRAINTS;
DROP TABLE STATUS CASCADE CONSTRAINTS;
DROP TABLE POST CASCADE CONSTRAINTS;
DROP TABLE THREAD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE CLUBS CASCADE CONSTRAINTS;
DROP TABLE FRIENDS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

-- TABLES CREATION
CREATE TABLE USER_STATUS (
  id          number(10) NOT NULL, 
  description varchar2(255) NOT NULL, 
  PRIMARY KEY (id));
  
CREATE TABLE OPENINGS (
  id        number(10, 0) NOT NULL, 
  name      varchar2(255) NOT NULL, 
  movements varchar2(1999) NOT NULL, 
  PRIMARY KEY (id));
  
CREATE TABLE GAMES (
  id               number(10, 0) NOT NULL, 
  movements        varchar2(1999), 
  game_result      integer,   -- 0 - draw, 1 - first player wins, 2 - second player wins.
  started_at       timestamp(6) NOT NULL, 
  first_player_id  number(10), 
  second_player_id number(10), 
  PRIMARY KEY (id));
  
CREATE TABLE STATUS (
  id          number(10, 0) NOT NULL, 
  description varchar2(255) NOT NULL, 
  PRIMARY KEY (id));
  
CREATE TABLE POST (
  id         number(10, 0) NOT NULL, 
  content    varchar2(1023) NOT NULL, 
  created_at timestamp(6) NOT NULL, 
  thread_id  number(10, 0) NOT NULL, 
  user_id    number(10) NOT NULL, 
  status_id  number(10, 0) NOT NULL, 
  PRIMARY KEY (id));
  
CREATE TABLE THREAD (
  id          number(10, 0) NOT NULL, 
  name        varchar2(255) NOT NULL, 
  description varchar2(1023) NOT NULL, 
  created_at  timestamp(6) NOT NULL, 
  user_id     number(10) NOT NULL, 
  status_id   number(10, 0) NOT NULL, 
  category_id number(10, 0) NOT NULL, 
  PRIMARY KEY (id));
  
CREATE TABLE CATEGORY (
  id          number(10, 0) NOT NULL, 
  name        varchar2(255) NOT NULL, 
  description varchar2(511) NOT NULL,
  PRIMARY KEY (id));
  
CREATE TABLE CLUBS (
  id     number(10) NOT NULL, 
  name   varchar2(255) UNIQUE, 
  rating number(10, 0) NOT NULL, 
  PRIMARY KEY (id));
  
CREATE TABLE FRIENDS (
  first_user_id  number(10) NOT NULL, 
  second_user_id number(10) NOT NULL, 
  PRIMARY KEY (first_user_id, 
  second_user_id));
  
CREATE TABLE USERS (
  id         number(10) NOT NULL, 
  name       varchar2(255) NOT NULL, 
  email      varchar2(255) NOT NULL, 
  nickname   varchar2(255) NOT NULL, 
  password   varchar2(100),
  facebook_id varchar2(100),
  wins       number(10, 0) NOT NULL, 
  looses     number(10, 0) NOT NULL, 
  draws      number(10, 0) NOT NULL, 
  created_at timestamp(6) NOT NULL, 
  status_id  number(10) NOT NULL, 
  club_id    number(10),
  token varchar2(2000),
  PRIMARY KEY (id));

-- TABLES FOREIGN KEY CONSTRAINT
ALTER TABLE POST ADD CONSTRAINT POST_THREAD_ID_FK FOREIGN KEY (thread_id) REFERENCES THREAD (id);
ALTER TABLE THREAD ADD CONSTRAINT THREAD_STATUS_ID_FK FOREIGN KEY (status_id) REFERENCES STATUS (id);
ALTER TABLE POST ADD CONSTRAINT POST_USER_ID_FK FOREIGN KEY (user_id) REFERENCES USERS (id);
ALTER TABLE THREAD ADD CONSTRAINT THREAD_USER_ID_FK FOREIGN KEY (user_id) REFERENCES USERS (id);
ALTER TABLE THREAD ADD CONSTRAINT THREAD_CATEGORY_ID_FK FOREIGN KEY (category_id) REFERENCES CATEGORY (id);
ALTER TABLE USERS ADD CONSTRAINT USERS_CLUB_ID_FK FOREIGN KEY (club_id) REFERENCES CLUBS (id);
ALTER TABLE GAMES ADD CONSTRAINT GAMES_SECOND_PLAYER_ID_FK FOREIGN KEY (second_player_id) REFERENCES USERS (id);
ALTER TABLE GAMES ADD CONSTRAINT GAMES_FIRST_PLAYER_ID_FK FOREIGN KEY (first_player_id) REFERENCES USERS (id);
ALTER TABLE POST ADD CONSTRAINT POST_STATUS_ID_FK FOREIGN KEY (status_id) REFERENCES STATUS (id);
ALTER TABLE FRIENDS ADD CONSTRAINT FRIENDS_FIRST_USER_ID_FK FOREIGN KEY (second_user_id) REFERENCES USERS (id);
ALTER TABLE FRIENDS ADD CONSTRAINT FRIENDS_SECOND_USER_ID_FK FOREIGN KEY (first_user_id) REFERENCES USERS (id);
ALTER TABLE USERS ADD CONSTRAINT USER_STATUS_ID_FK FOREIGN KEY (status_id) REFERENCES USER_STATUS (id);

-- --TABLES INDEXES
--
--CREATE INDEX USER_STATUS_id 
--  ON USER_STATUS (id);
--CREATE INDEX OPENINGS_id 
--  ON OPENINGS (id);
--CREATE INDEX GAMES_id 
--  ON GAMES (id);
--CREATE INDEX STATUS_id 
--  ON STATUS (id);
--CREATE INDEX POST_id 
--  ON POST (id);
--CREATE INDEX THREAD_id 
--  ON THREAD (id);
--CREATE INDEX CATEGORY_id 
--  ON CATEGORY (id);
--CREATE INDEX CLUBS_id 
--  ON CLUBS (id);
--CREATE INDEX USERS_id 
--  ON USERS (id);
--  
-- 10K entrie in some tables
/
commit;
