DROP INDEX USERS_NICKNAME_INDEX;
CREATE UNIQUE INDEX USERS_NICKNAME_INDEX ON USERS (NICKNAME);

DROP INDEX FRIENDS_USER1_INDEX;
CREATE UNIQUE INDEX FRIENDS_USER1_INDEX ON FRIENDS (FIRST_USER_ID);

DROP INDEX FRIENDS_USER2_INDEX;
CREATE UNIQUE INDEX FRIENDS_USER2_INDEX ON FRIENDS (SECOND_USER_ID);
commit;