DROP INDEX USERS_NICKNAME_INDEX;
CREATE UNIQUE INDEX USERS_NICKNAME_INDEX ON USERS (NICKNAME);

DROP INDEX GAMES_PLAYERS1_INDEX;
CREATE UNIQUE INDEX GAMES_PLAYERS1_INDEX ON GAMES (FIRST_PLAYER_ID);

DROP INDEX GAMES_PLAYERS2_INDEX;
CREATE UNIQUE INDEX GAMES_PLAYERS2_INDEX ON GAMES (SECOND_PLAYER_ID);

DROP INDEX FRIENDS_USER1_INDEX;
CREATE UNIQUE INDEX FRIENDS_USER1_INDEX ON FRIENDS (FIRST_USER_ID);

DROP INDEX FRIENDS_USER2_INDEX;
CREATE UNIQUE INDEX FRIENDS_USER2_INDEX ON FRIENDS (SECOND_USER_ID);

DROP INDEX CLUBS_NAME_INDEX;
CREATE UNIQUE INDEX CLUBS_NAME_INDEX ON CLUBS (NAME);

DROP INDEX CLUBS_RATING_INDEX;
CREATE UNIQUE INDEX CLUBS_RATING_INDEX ON CLUBS (RATING);
commit;